# The live image has an empty /boot, so copy the kernel from the ISO.
---
dontChroot: true
timeout: 60
script:
    - "cp /run/archiso/bootmnt/alnix/boot/x86_64/vmlinuz-linux ${ROOT}/boot/vmlinuz-linux"
